import{useState}from'react';
import{calculateGarageBonus,readGarageBonusRules,saveGarageBonusRules}from'./garageBonusSettings';
import{useGarageTimers}from'./garageTimers';

type Job={technician:string;labourMinutes:number;bookedDate?:string};
export function BonusPerformanceWidget({technicians,jobs}:{technicians:string[];jobs:Job[]}){
 const{state,now}=useGarageTimers(),[period,setPeriod]=useState<'day'|'week'|'month'|'year'>('week'),[selectedDate,setSelectedDate]=useState(()=>new Date().toISOString().slice(0,10)),[rules,setRules]=useState(readGarageBonusRules),[editing,setEditing]=useState(false),chosen=new Date(`${selectedDate}T12:00:00`),start=Number.isNaN(chosen.getTime())?new Date(now):new Date(chosen),end=new Date(start);
 if(period==='day'){start.setHours(0,0,0,0);end.setHours(24,0,0,0)}if(period==='week'){start.setDate(start.getDate()-((start.getDay()+6)%7));start.setHours(0,0,0,0);end.setTime(start.getTime()+7*86400000)}if(period==='month'){start.setDate(1);start.setHours(0,0,0,0);end.setMonth(start.getMonth()+1,1);end.setHours(0,0,0,0)}if(period==='year'){start.setMonth(0,1);start.setHours(0,0,0,0);end.setFullYear(start.getFullYear()+1,0,1);end.setHours(0,0,0,0)}
 const target=period==='day'?8:period==='week'?40:Array.from({length:Math.ceil((end.getTime()-start.getTime())/86400000)},(_,i)=>new Date(start.getTime()+i*86400000)).filter(date=>date.getDay()>0&&date.getDay()<6).length*8;
 const rows=technicians.map(tech=>{const events=state.events.filter(event=>event.tech===tech&&event.at>=start.getTime()&&event.at<end.getTime()),dates=[...new Set(events.map(event=>new Date(event.at).toISOString().slice(0,10)))],worked=dates.reduce((sum,date)=>{const daily=events.filter(event=>new Date(event.at).toISOString().slice(0,10)===date),first=Math.min(...daily.map(event=>event.at)),stops=daily.filter(event=>event.action==='manager-stop').map(event=>event.at),session=state.sessions[tech],live=session&&new Date(session.startedAt).toISOString().slice(0,10)===date?now:0,last=stops.length?Math.max(...stops,live):live,lunch=state.lunches[`${date}:${tech}`]?.used?3600000:0;return sum+(!Number.isFinite(first)||!last?0:Math.max(0,last-first-lunch))},0)/3600000,billed=jobs.filter(job=>job.technician===tech&&(!job.bookedDate||(new Date(job.bookedDate)>=start&&new Date(job.bookedDate)<end))).reduce((sum,job)=>sum+Number(job.labourMinutes||0)/60,0),efficiency=worked?billed/worked*100:0,attendance=Math.min(100,worked/target*100),bonus=calculateGarageBonus(efficiency,attendance,rules);return{tech,worked,billed,efficiency,attendance,...bonus}}),label=period==='day'?start.toLocaleDateString('en-IE'):period==='year'?String(start.getFullYear()):`${start.toLocaleDateString('en-IE')} – ${new Date(end.getTime()-86400000).toLocaleDateString('en-IE')}`;
 const update=(key:keyof typeof rules,value:string)=>setRules(current=>({...current,[key]:Math.max(0,Number(value)||0)})),performanceClass=(efficiency:number,attendance:number)=>efficiency>=rules.extraStartsAt&&attendance>=rules.minimumAttendance?'excellent':efficiency>=rules.minimumEfficiency&&attendance>=rules.minimumAttendance?'qualified':efficiency>=rules.minimumEfficiency*.8&&attendance>=rules.minimumAttendance*.8?'close':'behind';
 return <section className="bonusPerformanceWidget"><header><div><small>BONUS TRACKER</small><h3>Technician efficiency and bonus eligibility</h3><p>Standard target for this {period}: {target} hours. Efficiency is never capped.</p></div><b>{label}</b></header><div className="bonusWidgetFilters"><div className="bonusWidgetPeriods">{(['day','week','month','year']as const).map(value=><button type="button" className={period===value?'active':''} onClick={()=>setPeriod(value)} key={value}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div><label><span>Select date</span><input type="date" value={selectedDate} onChange={event=>setSelectedDate(event.target.value)}/></label><button type="button" className="bonusWidgetPresent" onClick={()=>setSelectedDate(new Date().toISOString().slice(0,10))}>Today</button><button type="button" className="bonusWidgetEdit" onClick={()=>setEditing(value=>!value)}>{editing?'Close rules':'Edit bonus rules'}</button></div>{editing&&<div className="bonusWidgetRuleEditor">{([['minimumEfficiency','Minimum efficiency %'],['minimumAttendance','Minimum attendance %'],['baseBonus','Base bonus €'],['extraStartsAt','Extra starts at %'],['extraPerPercent','Extra € per 1%'],['maximumExtra','Maximum extra €']]as const).map(([key,labelText])=><label key={key}><span>{labelText}</span><input type="number" min="0" step="0.1" value={rules[key]} onChange={event=>update(key,event.target.value)}/></label>)}<button type="button" onClick={()=>{saveGarageBonusRules(rules);setEditing(false)}}>Save bonus rules</button></div>}<div className="bonusPerformanceLegend"><span className="behind">Below target</span><span className="close">Nearly there</span><span className="qualified">Qualified</span><span className="excellent">Extra-bonus level</span></div><div className="bonusPerformanceHead"><b>Technician</b><b>Worked</b><b>Billed</b><b>Efficiency</b><b>Attendance</b><b>Bonus</b><b>Amount</b></div>{rows.map(row=><div className="bonusPerformanceRow" key={row.tech}><strong className={performanceClass(row.efficiency,row.attendance)}>{row.tech}</strong><span>{row.worked.toFixed(2)} hrs</span><span>{row.billed.toFixed(2)} hrs</span><span>{row.efficiency.toFixed(1)}%</span><span>{row.attendance.toFixed(1)}%</span><em>{row.qualifies?`${row.eligibility.toFixed(1)}%`:'Not qualified'}</em><span>€{row.amount.toFixed(2)}</span></div>)}<footer><b>Current rules:</b> qualify at {rules.minimumEfficiency}% efficiency and {rules.minimumAttendance}% attendance · base €{rules.baseBonus.toFixed(2)} · extra €{rules.extraPerPercent.toFixed(2)} per 1% above {rules.extraStartsAt}% · maximum extra €{rules.maximumExtra.toFixed(2)}.</footer></section>;
}
