import React,{useEffect,useMemo,useState}from'react';

type Session={jobId:string;homeJobId:string;mode:'own'|'help';startedAt:number};
type TimerEvent={at:number;tech:string;jobId:string;action:string;reason:string};
type TimerState={sessions:Record<string,Session>;consumed:Record<string,number>;firstStarts:Record<string,number>;lunches:Record<string,{used:boolean;endsAt:number;returnJobId:string}>;events:TimerEvent[]};
type TimerJob={id:string;reg:string;technician:string;remainingMinutes:number};
const key='aa-garage-timer-system-v1',changed='aa-garage-timers-changed';
const empty=():TimerState=>({sessions:{},consumed:{},firstStarts:{},lunches:{},events:[]});
const read=():TimerState=>{try{return{...empty(),...JSON.parse(localStorage.getItem(key)||'null')}}catch{return empty()}};
const save=(state:TimerState)=>{localStorage.setItem(key,JSON.stringify(state));window.dispatchEvent(new CustomEvent(changed))};
const dayKey=(tech:string,now=Date.now())=>`${new Date(now).toISOString().slice(0,10)}:${tech}`;
const settle=(state:TimerState,now=Date.now())=>{const next={...state,consumed:{...state.consumed},sessions:{...state.sessions}};Object.values(next.sessions).forEach(session=>{next.consumed[session.jobId]=(next.consumed[session.jobId]||0)+Math.max(0,now-session.startedAt)/1000;session.startedAt=now});return next};
const record=(state:TimerState,tech:string,jobId:string,action:string,reason:string,at=Date.now())=>({...state,events:[...state.events,{at,tech,jobId,action,reason}].slice(-1000)});
export function useGarageTimers(){const[state,setState]=useState(read),[now,setNow]=useState(Date.now());useEffect(()=>{const sync=()=>setState(read());window.addEventListener(changed,sync);const tick=window.setInterval(()=>setNow(Date.now()),1000);return()=>{window.removeEventListener(changed,sync);clearInterval(tick)}},[]);return{state,now}};
export function activeTechnicians(state:TimerState,jobId:string){return Object.entries(state.sessions).filter(([,session])=>session.jobId===jobId).map(([tech])=>tech)}
export function remainingSeconds(state:TimerState,job:TimerJob,now=Date.now()){const settled=state.consumed[job.id]||0,live=Object.values(state.sessions).filter(session=>session.jobId===job.id).reduce((sum,session)=>sum+Math.max(0,now-session.startedAt)/1000,0);return Math.max(0,job.remainingMinutes*60-settled-live)}
export function startTechnicianJob(tech:string,jobId:string,reason='Started assigned job'){let state=settle(read());const previous=state.sessions[tech];if(previous)state=record(state,tech,previous.jobId,'switch-out',reason);state.sessions[tech]={jobId,homeJobId:jobId,mode:'own',startedAt:Date.now()};state.firstStarts[dayKey(tech)]??=Date.now();save(record(state,tech,jobId,'start',reason))}
export function switchTechnicianJob(tech:string,jobId:string,reason:string){if(!reason)return;startTechnicianJob(tech,jobId,reason)}
export function startLunch(tech:string){let state=settle(read()),session=state.sessions[tech],today=dayKey(tech);if(!session||state.lunches[today]?.used)return false;const now=Date.now(),endsAt=new Date(new Date(now).setHours(14,0,0,0)).getTime();delete state.sessions[tech];state.lunches[today]={used:true,endsAt,returnJobId:session.jobId};save(record(state,tech,session.jobId,'lunch','One-hour lunch pause'));return true}
export function resumeLunches(){let state=settle(read()),dirty=false,now=Date.now();Object.entries(state.lunches).forEach(([entry,lunch])=>{const tech=entry.split(':').slice(1).join(':');if(lunch.used&&lunch.endsAt<=now&&!state.sessions[tech]){state.sessions[tech]={jobId:lunch.returnJobId,homeJobId:lunch.returnJobId,mode:'own',startedAt:now};state=record(state,tech,lunch.returnJobId,'resume','Lunch ended automatically');dirty=true}});if(dirty)save(state)}
export function helpTechnician(helper:string,targetJobId:string){let state=settle(read()),current=state.sessions[helper];if(!current)return;state.sessions[helper]={jobId:targetJobId,homeJobId:current.mode==='help'?current.homeJobId:current.jobId,mode:'help',startedAt:Date.now()};save(record(state,helper,targetJobId,'help','Helping another technician'))}
export function returnToOwnJob(tech:string){let state=settle(read()),current=state.sessions[tech];if(!current||current.mode!=='help')return;state.sessions[tech]={jobId:current.homeJobId,homeJobId:current.homeJobId,mode:'own',startedAt:Date.now()};save(record(state,tech,current.homeJobId,'return','Returned to own job'))}
export function managerStopJob(manager:string,jobId:string,reason:string){if(!reason)return;let state=settle(read());Object.entries(state.sessions).forEach(([tech,session])=>{if(session.jobId===jobId){delete state.sessions[tech];state=record(state,manager,jobId,'manager-stop',`${reason} · ${tech}`)}});save(state)}
export function TimerReminders(){const{state,now}=useGarageTimers();useEffect(()=>{resumeLunches()},[now]);const time=new Date(now),minutes=time.getHours()*60+time.getMinutes(),actor=sessionStorage.getItem('aa-actor')||'Technician',session=state.sessions[actor],lunch=state.lunches[dayKey(actor,now)];if(minutes===13*60&&session)return <div className="timerReminder">Lunch reminder: use your one-hour lunch pause now if required.</div>;if(minutes===13*60+55&&lunch?.used)return <div className="timerReminder warning">Your timer will resume automatically at 2:00 PM.</div>;if(minutes===18*60&&session)return <div className="timerReminder warning">Finishing-time reminder: contact the Workshop Manager to stop or transfer this timer.</div>;return null}
export function TechnicianTimerPanel({job,jobs}:{job:TimerJob;jobs:TimerJob[]}){const{state,now}=useGarageTimers(),actor=sessionStorage.getItem('aa-actor')||'Technician',[choosing,setChoosing]=useState(false),session=state.sessions[actor],active=activeTechnicians(state,job.id),seconds=remainingSeconds(state,job,now),today=state.lunches[dayKey(actor)],others=jobs.filter(item=>item.id!==job.id&&activeTechnicians(state,item.id).length);return <section className="techTimerPanel"><b>{Math.floor(seconds/3600)}h {Math.floor(seconds%3600/60)}m {Math.floor(seconds%60)}s remaining</b>{active.length>0&&<small>Counting time: {active.join(', ')}</small>}{!session&&<button onClick={()=>startTechnicianJob(actor,job.id)}>Start job timer</button>}{session?.jobId===job.id&&session.mode==='own'&&<button disabled={!!today?.used} onClick={()=>startLunch(actor)}>{today?.used?'Lunch pause already used':'Start one-hour lunch'}</button>}{session?.mode==='help'&&<button onClick={()=>returnToOwnJob(actor)}>Return to my job</button>}{session&&session.jobId!==job.id&&!choosing&&<button onClick={()=>setChoosing(true)}>Switch to this job</button>}{choosing&&<div className="timerReasons">{['Vehicle finished','Vehicle needs parts','Vehicle needs test driven','Vehicle needs attention'].map(reason=><button key={reason} onClick={()=>{switchTechnicianJob(actor,job.id,reason);setChoosing(false)}}>{reason}</button>)}</div>}{session?.jobId===job.id&&session.mode==='own'&&others.map(other=><button key={other.id} onClick={()=>helpTechnician(actor,other.id)}>Help {other.technician}</button>)}</section>}
export function ManagerTimerPanel({job}:{job:TimerJob}){const{state,now}=useGarageTimers(),[stopping,setStopping]=useState(false),seconds=remainingSeconds(state,job,now),active=activeTechnicians(state,job.id),manager=sessionStorage.getItem('aa-actor')||'Workshop Manager';return <div className="managerTimerControl"><span>{Math.floor(seconds/3600)}h {Math.floor(seconds%3600/60)}m remaining · {active.length?active.join(', '):'No timer active'}</span>{active.length>0&&!stopping&&<button onClick={()=>setStopping(true)}>Stop timer</button>}{stopping&&<div>{['Vehicle finished','Vehicle needs parts','Vehicle needs test driven','Job stopped by manager'].map(reason=><button key={reason} onClick={()=>{managerStopJob(manager,job.id,reason);setStopping(false)}}>{reason}</button>)}</div>}</div>}
export function FirstJobReport({technicians}:{technicians:string[]}){const{state}=useGarageTimers();return <section className="firstJobReport"><b>Technician first-job report</b>{technicians.map(tech=>{const at=state.firstStarts[dayKey(tech)];return <span key={tech}>{tech}: {at?new Date(at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'Not started'}</span>})}</section>}
