import {supabaseUserRequest} from './supabase'

const context=()=>({token:sessionStorage.getItem('aa-cloud-access-token')||'',organizationId:sessionStorage.getItem('aa-organization-id')||'',actorId:sessionStorage.getItem('aa-actor-id')||''})
const localCards=()=>{const cards:any[]=[];for(const key of Object.keys(localStorage)){if(key==='aa-garage-created-job-cards'||key.startsWith('aa-job-cards-'))try{const rows=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(rows))cards.push(...rows.filter(row=>/^JC-/i.test(String(row.id||''))))}catch{}}return Array.from(new Map(cards.map(card=>[card.id,card])).values())}
const cardTotals=(card:any)=>{const consumables=Number(card.consumablesWaste??(Number(card.consumables?.amount||0)+Number(card.waste?.amount||0)))||0;let subtotal=consumables,vat=consumables*Number(card.consumablesVatRate||0)/100;for(const job of card.jobs||[]){const labour=Number(job.labourHours)*Number(job.labourRate);subtotal+=labour;vat+=labour*Number(job.labourVatRate||0)/100;const parts=(job.parts||[]).length?job.parts:(card.lines||[]).filter((line:any)=>line.jobId===job.id);for(const part of parts){const net=Number(part.quantity||1)*Number(part.price||0);subtotal+=net;vat+=net*Number(part.vatRate||0)/100}}return{subtotal,vat,total:subtotal+vat}}

async function performGarageJobCardSync(){
 const{token,organizationId,actorId}=context();if(!token||!organizationId)return
 const[customers,vehicles,parts,profiles,documents]=await Promise.all([supabaseUserRequest<any[]>(`customers?organization_id=eq.${organizationId}&select=id,name`,token),supabaseUserRequest<any[]>(`vehicles?organization_id=eq.${organizationId}&select=id,customer_id,registration`,token),supabaseUserRequest<any[]>(`parts?organization_id=eq.${organizationId}&select=id,part_number,name,cost_price`,token),supabaseUserRequest<any[]>('profiles?select=id,full_name',token),supabaseUserRequest<any[]>(`documents?organization_id=eq.${organizationId}&select=id,document_type,document_number`,token)])
 for(const card of localCards()){
  const customer=customers.find(row=>String(row.name).trim().toLowerCase()===String(card.customer).trim().toLowerCase()),registration=String(card.vehicle||'').split(' · ')[0].trim().toUpperCase(),vehicle=vehicles.find(row=>row.customer_id===customer?.id&&String(row.registration).toUpperCase()===registration);if(!customer||!vehicle)continue
  const existing=documents.find(row=>row.document_type==='job_card'&&row.document_number===card.id),source=documents.find(row=>row.document_type==='estimate'&&row.document_number===(card.sourceQuoteId||card.sourceId)),amount=cardTotals(card),meta={requestedWork:card.requestedWork||'',customerNote:card.customerNote||'',additionalInformation:card.additionalInformation||'',consumablesVatRate:card.consumablesVatRate||0,checklists:card.checklists||[],convertedToId:card.convertedToId||card.invoiceId||null,lines:card.lines||[]},body={organization_id:organizationId,document_type:'job_card',document_number:card.id,customer_id:customer.id,vehicle_id:vehicle.id,source_document_id:source?.id||null,status:card.status||'draft',notes:JSON.stringify(meta),consumables:Number(card.consumablesWaste??card.consumables?.amount)||0,waste:Number(card.waste?.amount)||0,subtotal:amount.subtotal,vat_total:amount.vat,total:amount.total,locked_at:card.locked?new Date().toISOString():null,created_by:actorId||null,created_at:card.createdAt||new Date().toISOString()}
  let documentId=existing?.id;if(documentId){await supabaseUserRequest(`documents?id=eq.${documentId}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});await supabaseUserRequest(`document_jobs?document_id=eq.${documentId}`,token,{method:'DELETE',headers:{Prefer:'return=minimal'}})}else{const rows=await supabaseUserRequest<{id:string}[]>('documents?select=id',token,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});documentId=rows[0].id;documents.push({id:documentId,document_type:'job_card',document_number:card.id})}
  for(let position=0;position<(card.jobs||[]).length;position++){const job=card.jobs[position],technician=profiles.find(row=>String(row.full_name).toLowerCase()===String(job.technician||'').toLowerCase()),jobRows=await supabaseUserRequest<{id:string}[]>('document_jobs?select=id',token,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({organization_id:organizationId,document_id:documentId,name:job.name,description:job.description||'',labour_hours:Number(job.labourHours),labour_rate:Number(job.labourRate)||0,labour_vat_rate:Number(job.labourVatRate)||0,technician_id:technician?.id||null,position})}),documentJobId=jobRows[0].id,jobParts=(job.parts||[]).length?job.parts:(card.lines||[]).filter((line:any)=>line.jobId===job.id);for(let partPosition=0;partPosition<jobParts.length;partPosition++){const part=jobParts[partPosition],catalogue=parts.find(row=>String(row.name).toLowerCase()===String(part.name).toLowerCase());await supabaseUserRequest('document_parts',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({organization_id:organizationId,document_job_id:documentJobId,part_id:catalogue?.id||null,part_number:catalogue?.part_number||null,name:part.name,quantity:Number(part.quantity)||1,unit_cost:Number(catalogue?.cost_price)||0,unit_price:Number(part.price)||0,vat_rate:Number(part.vatRate)||0,fitted:false,position:partPosition})})}}
 }
}

let activeSync:Promise<void>|null=null
export async function syncLocalGarageJobCardsToCloud(){
 if(activeSync)return activeSync
 activeSync=performGarageJobCardSync()
 try{await activeSync}finally{activeSync=null}
}

export async function hydrateGarageJobCardsFromCloud(){
 const{token,organizationId}=context();if(!token||!organizationId)return
 const[documents,jobs,parts,customers,vehicles,profiles]=await Promise.all([supabaseUserRequest<any[]>(`documents?organization_id=eq.${organizationId}&document_type=eq.job_card&select=*`,token),supabaseUserRequest<any[]>(`document_jobs?organization_id=eq.${organizationId}&select=*`,token),supabaseUserRequest<any[]>(`document_parts?organization_id=eq.${organizationId}&select=*`,token),supabaseUserRequest<any[]>(`customers?organization_id=eq.${organizationId}&select=id,name`,token),supabaseUserRequest<any[]>(`vehicles?organization_id=eq.${organizationId}&select=id,registration,make,model`,token),supabaseUserRequest<any[]>('profiles?select=id,full_name',token)]);if(!documents.length)return
 const hydrated=documents.flatMap(document=>{const customer=customers.find(row=>row.id===document.customer_id),vehicle=vehicles.find(row=>row.id===document.vehicle_id);if(!customer||!vehicle)return[];let meta:any={};try{meta=JSON.parse(document.notes||'{}')}catch{}const cardJobs=jobs.filter(job=>job.document_id===document.id).sort((a,b)=>a.position-b.position).map(job=>({id:`cloud-job-${job.id}`,name:job.name,description:job.description||'',labourHours:Number(job.labour_hours),labourRate:Number(job.labour_rate),labourVatRate:Number(job.labour_vat_rate),technician:profiles.find(row=>row.id===job.technician_id)?.full_name||'Unassigned',parts:parts.filter(part=>part.document_job_id===job.id).sort((a,b)=>a.position-b.position).map(part=>({id:`cloud-part-line-${part.id}`,name:part.name,description:'',quantity:Number(part.quantity),price:Number(part.unit_price),vatRate:Number(part.vat_rate)}))}));return[{id:document.document_number,type:'job-card',customer:customer.name,vehicle:`${vehicle.registration} · ${vehicle.make} ${vehicle.model}`,jobs:cardJobs,createdAt:document.created_at,status:document.status,locked:!!document.locked_at,requestedWork:meta.requestedWork||'',customerNote:meta.customerNote||'',additionalInformation:meta.additionalInformation||'',consumablesWaste:Number(document.consumables)+Number(document.waste),consumablesVatRate:Number(meta.consumablesVatRate)||0,checklists:meta.checklists||[],convertedToId:meta.convertedToId||undefined,lines:cardJobs.flatMap((job:any)=>job.parts.map((part:any)=>({...part,jobId:job.id,type:'part',unit:'each'})))}]})
 let local:any[]=[];try{local=JSON.parse(localStorage.getItem('aa-garage-created-job-cards')||'[]')}catch{};const merged=[...hydrated,...local.filter(card=>!hydrated.some(cloud=>cloud.id===card.id))];localStorage.setItem('aa-garage-created-job-cards',JSON.stringify(merged));for(const card of hydrated){const key=`aa-job-cards-${card.customer}`;let rows:any[]=[];try{rows=JSON.parse(localStorage.getItem(key)||'[]')}catch{};localStorage.setItem(key,JSON.stringify([card,...rows.filter(row=>row.id!==card.id)]))}window.dispatchEvent(new Event('aa-garage-job-cards-updated'))
}

let started=false
export function startGarageJobCardsCloudSync(){if(started)return;started=true;const nativeSet=Storage.prototype.setItem;let timer:number|undefined;Storage.prototype.setItem=function(key:string,value:string){nativeSet.call(this,key,value);if(this===localStorage&&(key==='aa-garage-created-job-cards'||key.startsWith('aa-job-cards-'))){clearTimeout(timer);timer=window.setTimeout(()=>void syncLocalGarageJobCardsToCloud().catch(error=>window.dispatchEvent(new CustomEvent('aa-cloud-sync-error',{detail:error instanceof Error?error.message:'Job card cloud sync failed.'}))),200)}}}
