import {readGarageEmployees} from './garageEmployees'
import {supabaseUserRequest} from './supabase'

const settingKeys=['aa-garage-rates-v1','aa-garage-job-card-customer-note','aa-garage-invoice-customer-note','aa-garage-company-details-v1','aa-garage-job-names-v1','aa-garage-job-reminders-v1','aa-garage-custom-jobs','aa-garage-bonus-rules-v1','aa-garage-leave-records-v1','aa-employee-permissions','aa-rental-fleet-vehicles','aa-rental-check-note-options','aa-rental-check-groups','aa-unified-work-items-v1','aa-completed-workshop-areas','aa-garage-management-jobs-v1','aa-holdings-ideas-v1'] as const
const employeesKey='aa-garage-employees-v1'
const context=()=>({token:sessionStorage.getItem('aa-cloud-access-token')||'',organizationId:sessionStorage.getItem('aa-organization-id')||'',actorId:sessionStorage.getItem('aa-actor-id')||''})
const parse=(raw:string|null)=>{if(raw===null)return null;try{return JSON.parse(raw)}catch{return raw}}
const safeEmployees=()=>readGarageEmployees().map(({passcode:_,...employee})=>employee)

async function performSync(){const{token,organizationId,actorId}=context();if(!token||!organizationId)return;const existing=await supabaseUserRequest<any[]>(`organization_settings?organization_id=eq.${organizationId}&select=setting_key`,token),values=new Map<string,unknown>();settingKeys.forEach(key=>{const value=parse(localStorage.getItem(key));if(value!==null)values.set(key,value)});values.set(employeesKey,safeEmployees());for(const[key,value]of values){const body={organization_id:organizationId,setting_key:key,setting_value:value,updated_by:actorId||null,updated_at:new Date().toISOString()};if(existing.some(row=>row.setting_key===key))await supabaseUserRequest(`organization_settings?organization_id=eq.${organizationId}&setting_key=eq.${encodeURIComponent(key)}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else await supabaseUserRequest('organization_settings',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}}
let activeSync:Promise<void>|null=null
export async function syncGarageSettingsToCloud(){if(activeSync)return activeSync;activeSync=performSync();try{await activeSync}finally{activeSync=null}}

export async function hydrateGarageSettingsFromCloud(){const{token,organizationId}=context();if(!token||!organizationId)return;const rows=await supabaseUserRequest<any[]>(`organization_settings?organization_id=eq.${organizationId}&select=setting_key,setting_value`,token);rows.forEach(row=>{if(row.setting_key===employeesKey){const current=readGarageEmployees(),passcodes=new Map(current.map(employee=>[employee.id,employee.passcode]));localStorage.setItem(employeesKey,JSON.stringify((Array.isArray(row.setting_value)?row.setting_value:[]).map((employee:any)=>({...employee,passcode:passcodes.get(employee.id)||''}))))}else localStorage.setItem(row.setting_key,JSON.stringify(row.setting_value))});['aa-garage-rates-updated','aa-garage-company-details-updated','aa-garage-job-names-updated','aa-garage-reminders-updated','aa-garage-custom-jobs-updated','aa-garage-bonus-rules-updated','aa-garage-leave-updated','aa-garage-employees-updated','aa-garage-jobs-updated','aa-holdings-updated','aa-rental-safety-checks-updated'].forEach(name=>window.dispatchEvent(new Event(name)))}

let started=false
export function startGarageSettingsCloudSync(){if(started)return;started=true;const nativeSet=Storage.prototype.setItem;let timer:number|undefined;Storage.prototype.setItem=function(key:string,value:string){nativeSet.call(this,key,value);if(this===localStorage&&(key===employeesKey||(settingKeys as readonly string[]).includes(key))){clearTimeout(timer);timer=window.setTimeout(()=>void syncGarageSettingsToCloud().catch(error=>window.dispatchEvent(new CustomEvent('aa-cloud-sync-error',{detail:error instanceof Error?error.message:'Settings cloud sync failed.'}))),200)}}}
