import {supabaseUserRequest} from './supabase'
const context=()=>({token:sessionStorage.getItem('aa-cloud-access-token')||'',organizationId:sessionStorage.getItem('aa-organization-id')||'',actorId:sessionStorage.getItem('aa-actor-id')||''})
const invoiceKeys=()=>Object.keys(localStorage).filter(key=>key.startsWith('aa-garage-invoices-'))
const localInvoices=()=>invoiceKeys().flatMap(key=>{try{const rows=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}}).filter(row=>/^INV-/i.test(String(row.id||'')))
const uniqueInvoices=()=>Array.from(new Map(localInvoices().map(invoice=>[invoice.id,invoice])).values())
const methodToCloud=(method:string)=>method==='Bank transfer'?'bank_transfer':String(method||'Cash').toLowerCase()
const methodFromCloud=(method:string)=>method==='bank_transfer'?'Bank transfer':method?method[0].toUpperCase()+method.slice(1):'Cash'
const totals=(invoice:any)=>{const consumables=Number(invoice.consumablesWaste??(Number(invoice.consumables?.amount||0)+Number(invoice.waste?.amount||0)))||0;let subtotal=consumables,vat=consumables*Number(invoice.consumablesVatRate||0)/100;for(const job of invoice.jobs||[]){const labour=Number(job.labourHours)*Number(job.labourRate);subtotal+=labour;vat+=labour*Number(job.labourVatRate||0)/100;const lines=(job.parts||[]).length?job.parts:(invoice.lines||[]).filter((line:any)=>line.jobId===job.id);for(const line of lines){const net=Number(line.quantity||1)*Number(line.price||0);subtotal+=net;vat+=net*Number(line.vatRate||0)/100}}return{subtotal,vat,total:subtotal+vat}}

async function performSync(){
 const{token,organizationId,actorId}=context();if(!token||!organizationId)return
 const[customers,vehicles,parts,documents]=await Promise.all([supabaseUserRequest<any[]>(`customers?organization_id=eq.${organizationId}&select=id,name`,token),supabaseUserRequest<any[]>(`vehicles?organization_id=eq.${organizationId}&select=id,customer_id,registration`,token),supabaseUserRequest<any[]>(`parts?organization_id=eq.${organizationId}&select=id,part_number,name,cost_price`,token),supabaseUserRequest<any[]>(`documents?organization_id=eq.${organizationId}&select=id,document_type,document_number`,token)])
 for(const invoice of uniqueInvoices()){
  const customer=customers.find(row=>String(row.name).trim().toLowerCase()===String(invoice.customer).trim().toLowerCase()),registration=String(invoice.vehicle||'').split(' · ')[0].trim().toUpperCase(),vehicle=vehicles.find(row=>row.customer_id===customer?.id&&String(row.registration).toUpperCase()===registration);if(!customer||!vehicle)continue
  const existing=documents.find(row=>row.document_type==='invoice'&&row.document_number===invoice.id),sourceNumber=invoice.sourceId||invoice.sourceJobCardId,source=documents.find(row=>row.document_type==='job_card'&&row.document_number===sourceNumber),amount=totals(invoice),paid=Number(invoice.amountPaid??(invoice.payments||[]).reduce((sum:number,payment:any)=>sum+Number(payment.amount||0),0)),status=paid>=amount.total&&amount.total>0?'paid':paid>0?'partially_paid':'unpaid',meta={customerNote:invoice.customerNote||'',additionalInformation:invoice.additionalInformation||'',consumablesVatRate:invoice.consumablesVatRate||0,sourceQuoteId:invoice.sourceQuoteId||null},body={organization_id:organizationId,document_type:'invoice',document_number:invoice.id,customer_id:customer.id,vehicle_id:vehicle.id,source_document_id:source?.id||null,status,notes:JSON.stringify(meta),consumables:Number(invoice.consumablesWaste??invoice.consumables?.amount)||0,waste:Number(invoice.waste?.amount)||0,subtotal:amount.subtotal,vat_total:amount.vat,total:amount.total,locked_at:status==='paid'?new Date().toISOString():null,created_by:actorId||null,created_at:invoice.createdAt||new Date().toISOString()}
  let documentId=existing?.id;if(documentId){await supabaseUserRequest(`payments?invoice_id=eq.${documentId}`,token,{method:'DELETE',headers:{Prefer:'return=minimal'}});await supabaseUserRequest(`document_jobs?document_id=eq.${documentId}`,token,{method:'DELETE',headers:{Prefer:'return=minimal'}});await supabaseUserRequest(`documents?id=eq.${documentId}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}else{const rows=await supabaseUserRequest<any[]>('documents?select=id',token,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});documentId=rows[0].id;documents.push({id:documentId,document_type:'invoice',document_number:invoice.id})}
  for(let position=0;position<(invoice.jobs||[]).length;position++){const job=invoice.jobs[position],jobRows=await supabaseUserRequest<any[]>('document_jobs?select=id',token,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({organization_id:organizationId,document_id:documentId,name:job.name,description:job.description||'',labour_hours:Number(job.labourHours),labour_rate:Number(job.labourRate)||0,labour_vat_rate:Number(job.labourVatRate)||0,position})}),jobId=jobRows[0].id,jobParts=(job.parts||[]).length?job.parts:(invoice.lines||[]).filter((line:any)=>line.jobId===job.id);for(let partPosition=0;partPosition<jobParts.length;partPosition++){const line=jobParts[partPosition],catalogue=parts.find(row=>String(row.name).toLowerCase()===String(line.name).toLowerCase());await supabaseUserRequest('document_parts',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({organization_id:organizationId,document_job_id:jobId,part_id:catalogue?.id||null,part_number:catalogue?.part_number||null,name:line.name,quantity:Number(line.quantity)||1,unit_cost:Number(catalogue?.cost_price)||0,unit_price:Number(line.price)||0,vat_rate:Number(line.vatRate)||0,position:partPosition})})}}
  for(const payment of invoice.payments||[])await supabaseUserRequest('payments',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({organization_id:organizationId,invoice_id:documentId,amount:Number(payment.amount),method:methodToCloud(payment.method),paid_at:`${payment.date||new Date().toISOString().slice(0,10)}T12:00:00.000Z`,recorded_by:actorId||null})})
 }
}
let activeSync:Promise<void>|null=null
export async function syncGarageInvoicesToCloud(){if(activeSync)return activeSync;activeSync=performSync();try{await activeSync}finally{activeSync=null}}

export async function hydrateGarageInvoicesFromCloud(){
 const{token,organizationId}=context();if(!token||!organizationId)return
 const[documents,jobs,parts,payments,customers,vehicles]=await Promise.all([supabaseUserRequest<any[]>(`documents?organization_id=eq.${organizationId}&document_type=eq.invoice&select=*`,token),supabaseUserRequest<any[]>(`document_jobs?organization_id=eq.${organizationId}&select=*`,token),supabaseUserRequest<any[]>(`document_parts?organization_id=eq.${organizationId}&select=*`,token),supabaseUserRequest<any[]>(`payments?organization_id=eq.${organizationId}&select=*`,token),supabaseUserRequest<any[]>(`customers?organization_id=eq.${organizationId}&select=id,name`,token),supabaseUserRequest<any[]>(`vehicles?organization_id=eq.${organizationId}&select=id,registration,make,model`,token)]);if(!documents.length)return
 for(const document of documents){const customer=customers.find(row=>row.id===document.customer_id),vehicle=vehicles.find(row=>row.id===document.vehicle_id);if(!customer||!vehicle)continue;let meta:any={};try{meta=JSON.parse(document.notes||'{}')}catch{}const invoiceJobs=jobs.filter(job=>job.document_id===document.id).sort((a,b)=>a.position-b.position).map(job=>({id:`cloud-job-${job.id}`,name:job.name,description:job.description||'',labourHours:Number(job.labour_hours),labourRate:Number(job.labour_rate),labourVatRate:Number(job.labour_vat_rate),partName:'',partQuantity:1,partPrice:0,parts:parts.filter(part=>part.document_job_id===job.id).sort((a,b)=>a.position-b.position).map(part=>({id:`cloud-part-line-${part.id}`,name:part.name,description:'',quantity:Number(part.quantity),price:Number(part.unit_price),vatRate:Number(part.vat_rate)}))})),invoicePayments=payments.filter(payment=>payment.invoice_id===document.id).map(payment=>({id:`PAY-${payment.payment_number}`,number:payment.payment_number,amount:Number(payment.amount),date:String(payment.paid_at).slice(0,10),method:methodFromCloud(payment.method)})),invoice={id:document.document_number,type:'invoice',customer:customer.name,vehicle:`${vehicle.registration} · ${vehicle.make} ${vehicle.model}`,jobs:invoiceJobs,createdAt:document.created_at,sourceId:undefined,sourceQuoteId:meta.sourceQuoteId||undefined,consumablesWaste:Number(document.consumables)+Number(document.waste),consumablesVatRate:Number(meta.consumablesVatRate)||0,customerNote:meta.customerNote||'',additionalInformation:meta.additionalInformation||'',locked:document.status==='paid',amountPaid:invoicePayments.reduce((sum,payment)=>sum+payment.amount,0),payments:invoicePayments};const key=`aa-garage-invoices-${customer.name}`;let local:any[]=[];try{local=JSON.parse(localStorage.getItem(key)||'[]')}catch{};localStorage.setItem(key,JSON.stringify([invoice,...local.filter(row=>row.id!==invoice.id)]))}
 window.dispatchEvent(new Event('aa-garage-invoices-updated'))
}

let started=false
export function startGarageInvoicesCloudSync(){if(started)return;started=true;const nativeSet=Storage.prototype.setItem;let timer:number|undefined;Storage.prototype.setItem=function(key:string,value:string){nativeSet.call(this,key,value);if(this===localStorage&&key.startsWith('aa-garage-invoices-')){clearTimeout(timer);timer=window.setTimeout(()=>void syncGarageInvoicesToCloud().catch(error=>window.dispatchEvent(new CustomEvent('aa-cloud-sync-error',{detail:error instanceof Error?error.message:'Invoice cloud sync failed.'}))),200)}}}
