import {supabaseUserRequest} from './supabase'
const context=()=>({token:sessionStorage.getItem('aa-cloud-access-token')||'',organizationId:sessionStorage.getItem('aa-organization-id')||'',actorId:sessionStorage.getItem('aa-actor-id')||''})
const templatesKey='aa-garage-checklist-templates'
const readJson=(key:string,fallback:any)=>{try{return JSON.parse(localStorage.getItem(key)||'null')??fallback}catch{return fallback}}

export async function syncGarageChecklistsToCloud(){
 const{token,organizationId,actorId}=context();if(!token||!organizationId)return
 const templates:any[]=readJson(templatesKey,[]),cloudTemplates=await supabaseUserRequest<any[]>(`checklist_templates?organization_id=eq.${organizationId}&select=id,legacy_source_id`,token)
 for(const template of templates){const existing=cloudTemplates.find(row=>row.legacy_source_id===String(template.id)),body={organization_id:organizationId,legacy_source_id:String(template.id),name:template.name,definition:template,active:true,updated_at:new Date().toISOString()};if(existing)await supabaseUserRequest(`checklist_templates?id=eq.${existing.id}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else{const rows=await supabaseUserRequest<any[]>('checklist_templates?select=id,legacy_source_id',token,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)});cloudTemplates.push(...rows)}}
 const resultKeys=Object.keys(localStorage).filter(key=>key.startsWith('aa-garage-checklist-results-')),existingResults=await supabaseUserRequest<any[]>(`checklist_results?organization_id=eq.${organizationId}&select=id,local_job_key`,token),documents=await supabaseUserRequest<any[]>(`documents?organization_id=eq.${organizationId}&document_type=eq.job_card&select=id,document_number`,token)
 for(const key of resultKeys){const jobKey=key.slice('aa-garage-checklist-results-'.length),results=readJson(key,{}),saved=readJson(`aa-garage-checklist-saved-${jobKey}`,null),viewed=localStorage.getItem(`aa-garage-checklist-viewed-${jobKey}`),cardNumber=jobKey.includes(':')?jobKey.slice(0,jobKey.indexOf(':')):'',document=documents.find(row=>row.document_number===cardNumber),existing=existingResults.find(row=>row.local_job_key===jobKey),status=viewed&&saved?.savedAt===viewed?'reviewed':saved?'completed':'in_progress',body={organization_id:organizationId,document_id:document?.id||null,local_job_key:jobKey,template_id:null,results,status,completed_by:saved?actorId||null:null,completed_at:saved?.savedAt||null,reviewed_by:status==='reviewed'?actorId||null:null,reviewed_at:status==='reviewed'?new Date().toISOString():null,updated_at:new Date().toISOString()};if(existing)await supabaseUserRequest(`checklist_results?id=eq.${existing.id}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else await supabaseUserRequest('checklist_results',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}
}

export async function hydrateGarageChecklistsFromCloud(){
 const{token,organizationId}=context();if(!token||!organizationId)return
 const[templates,results]=await Promise.all([supabaseUserRequest<any[]>(`checklist_templates?organization_id=eq.${organizationId}&active=eq.true&select=definition`,token),supabaseUserRequest<any[]>(`checklist_results?organization_id=eq.${organizationId}&select=local_job_key,results,status,completed_at,reviewed_at`,token)])
 if(templates.length){const local:any[]=readJson(templatesKey,[]),cloud=templates.map(row=>row.definition),ids=new Set(cloud.map(item=>String(item.id)));localStorage.setItem(templatesKey,JSON.stringify([...cloud,...local.filter(item=>!ids.has(String(item.id)))]))}
 results.forEach(row=>{localStorage.setItem(`aa-garage-checklist-results-${row.local_job_key}`,JSON.stringify(row.results||{}));if(row.completed_at)localStorage.setItem(`aa-garage-checklist-saved-${row.local_job_key}`,JSON.stringify({savedAt:row.completed_at,technician:'Cloud user'}));if(row.status==='reviewed')localStorage.setItem(`aa-garage-checklist-viewed-${row.local_job_key}`,row.completed_at||row.reviewed_at||'reviewed')})
 window.dispatchEvent(new Event('aa-garage-checklists-updated'));results.forEach(row=>window.dispatchEvent(new CustomEvent('aa-garage-checklist-results-updated',{detail:{jobId:row.local_job_key}})))
}

let activeSync:Promise<void>|null=null,started=false
export async function queueGarageChecklistSync(){if(activeSync)return activeSync;activeSync=syncGarageChecklistsToCloud();try{await activeSync}finally{activeSync=null}}
export function startGarageChecklistsCloudSync(){if(started)return;started=true;const nativeSet=Storage.prototype.setItem,nativeRemove=Storage.prototype.removeItem;let timer:number|undefined;const schedule=()=>{clearTimeout(timer);timer=window.setTimeout(()=>void queueGarageChecklistSync().catch(error=>window.dispatchEvent(new CustomEvent('aa-cloud-sync-error',{detail:error instanceof Error?error.message:'Checklist cloud sync failed.'}))),200)};Storage.prototype.setItem=function(key:string,value:string){nativeSet.call(this,key,value);if(this===localStorage&&(key===templatesKey||key.startsWith('aa-garage-checklist-')))schedule()};Storage.prototype.removeItem=function(key:string){nativeRemove.call(this,key);if(this===localStorage&&key.startsWith('aa-garage-checklist-'))schedule()}}
