import {useEffect,useState} from 'react';
import {CheckCircle2,ExternalLink,KeyRound,LoaderCircle,Route,ShieldCheck} from 'lucide-react';
import './routalConnection.css';

type Stop={externalId:string;name:string;address:string;serviceMinutes:number;notes:string};
export function RoutalConnection({stops}:{stops:any[]}){
 const[configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[apiKey,setApiKey]=useState(''),[projectId,setProjectId]=useState('');
 useEffect(()=>{fetch('/api/routal/status').then(r=>r.json()).then(x=>setConfigured(Boolean(x.configured))).catch(()=>setConfigured(false))},[]);
 const request=async(path:string,body?:unknown)=>{setBusy(path);setMessage('');try{const response=await fetch(`/api/routal/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),result=await response.json();if(!response.ok)throw new Error(result.error||'The Routal request failed.');setMessage(path==='test-connection'?`Connected securely. Routal returned ${result.vehicles} vehicle${result.vehicles===1?'':'s'} for this project.`:`Test plan created in Routal with ${result.stops} stop${result.stops===1?'':'s'}. Open Routal Planner to review and optimise it.`)}catch(error){setMessage(error instanceof Error?error.message:'The Routal request failed.')}finally{setBusy('')}};
 const savePrivate=async()=>{setBusy('local-config');setMessage('');try{const response=await fetch('/api/routal/local-config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey,projectId})}),result=await response.json();if(!response.ok)throw new Error(result.error||'The private settings could not be saved.');setApiKey('');setProjectId('');setConfigured(true);setMessage('Private settings saved on this computer. You can now test the connection.')}catch(error){setMessage(error instanceof Error?error.message:'The private settings could not be saved.')}finally{setBusy('')}};
 const mapped:Stop[]=stops.map(m=>({externalId:m[0],name:m[1],address:`${m[2]}, Ireland`,serviceMinutes:18,notes:`Machine ${m[0]}; verified from the Address Summary sheet`}));
 const seededNames=['City Gym Lobby','TechPark Canteen','Central Hospital','Westside College','North Business Hub','FitLife Centre','Railway Offices','Harbour Workspace'],hasDemoLocations=stops.some(m=>seededNames.includes(String(m[1])));
 return <div className={`routalConnection ${configured?'connected':'notConfigured'}`}><div className="routalConnectionIcon">{configured?<ShieldCheck/>:<KeyRound/>}</div><div><em>SECURE ROUTAL CONNECTION</em><h3>{configured?'Server connection ready':'Private setup required'}</h3><p>{configured?'The API key is protected on the local server and is never sent to this browser.':'Paste the values here on the dashboard computer. They are saved only in the private local server file.'}</p>{!configured&&<div className="routalPrivateForm"><input required type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Paste Routal API key"/><input required autoComplete="off" value={projectId} onChange={e=>setProjectId(e.target.value)} placeholder="Paste Routal Project ID"/><button disabled={!!busy||!apiKey.trim()||!projectId.trim()} onClick={savePrivate}>{busy==='local-config'?<LoaderCircle className="spin"/>:<ShieldCheck/>}Save private settings</button></div>}{message&&<div className="routalMessage"><CheckCircle2 size={16}/>{message}</div>}{configured&&hasDemoLocations&&<div className="routalDemoWarning">The connection is live, but these machine locations are demonstration data. Add your real machine addresses before creating a Routal plan.</div>}</div><div className="routalConnectActions">{configured?<><button disabled={!!busy} onClick={()=>request('test-connection')}>{busy==='test-connection'?<LoaderCircle className="spin"/>:<ShieldCheck/>}Test connection</button><button disabled={!!busy||!mapped.length||hasDemoLocations} onClick={()=>request('test-plan',{stops:mapped.slice(0,1)})}>{busy==='test-plan'?<LoaderCircle className="spin"/>:<Route/>}{hasDemoLocations?'Add real locations first':'Create one-stop test'}</button></>:<span><KeyRound size={16}/>Local setup only</span>}<a href="https://planner.routal.com" target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open Routal</a></div></div>
}
