begin;

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  trading_name text,
  vat_number text,
  address text,
  postcode text,
  email text,
  phone text,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  email text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null check (role in ('owner','manager','front_of_house','technician','staff')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create or replace function public.current_organization_ids()
returns setof uuid
language sql
stable
security definer
set search_path = public
as $$
  select organization_id
  from public.organization_members
  where user_id = auth.uid() and active = true;
$$;

create or replace function public.has_organization_role(target_organization uuid, allowed_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.organization_members
    where organization_id = target_organization
      and user_id = auth.uid()
      and active = true
      and role = any(allowed_roles)
  );
$$;

revoke all on function public.current_organization_ids() from public;
revoke all on function public.has_organization_role(uuid, text[]) from public;
grant execute on function public.current_organization_ids() to authenticated;
grant execute on function public.has_organization_role(uuid, text[]) to authenticated;

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_number bigint generated by default as identity,
  customer_type text not null default 'personal' check (customer_type in ('personal','business')),
  name text not null,
  company_name text,
  email text,
  phone text,
  address text,
  postcode text,
  notes text,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, customer_number)
);

create table if not exists public.customer_contacts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  role text,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete restrict,
  registration text not null,
  make text not null,
  model text not null,
  year integer,
  vin text,
  mileage integer,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, registration)
);

create table if not exists public.suppliers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null,
  email text,
  phone text,
  created_at timestamptz not null default now(),
  unique (organization_id, name)
);

create table if not exists public.parts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  part_number text not null,
  name text not null,
  description text,
  product_group text,
  supplier_id uuid references public.suppliers(id) on delete set null,
  supplier_part_number text,
  cost_price numeric(12,2) not null default 0 check (cost_price >= 0),
  trade_price numeric(12,2) not null default 0 check (trade_price >= 0),
  selling_price numeric(12,2) not null default 0 check (selling_price >= 0),
  vat_rate numeric(5,2) not null default 13.50 check (vat_rate >= 0),
  stock_quantity numeric(12,2) not null default 0,
  minimum_stock numeric(12,2) not null default 0,
  maximum_stock numeric(12,2) not null default 0,
  bin_location text,
  nominal_code text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, part_number)
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_type text not null check (document_type in ('estimate','job_card','invoice')),
  document_number text not null,
  customer_id uuid not null references public.customers(id) on delete restrict,
  vehicle_id uuid not null references public.vehicles(id) on delete restrict,
  source_document_id uuid references public.documents(id) on delete set null,
  status text not null default 'draft',
  notes text,
  consumables numeric(12,2) not null default 0,
  waste numeric(12,2) not null default 0,
  subtotal numeric(12,2) not null default 0,
  vat_total numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  locked_at timestamptz,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, document_type, document_number)
);

create table if not exists public.document_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_id uuid not null references public.documents(id) on delete cascade,
  name text not null,
  description text,
  labour_hours numeric(8,2) not null check (labour_hours > 0),
  labour_rate numeric(12,2) not null default 0 check (labour_rate >= 0),
  labour_vat_rate numeric(5,2) not null default 13.50 check (labour_vat_rate >= 0),
  technician_id uuid references public.profiles(id),
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.document_parts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  document_job_id uuid not null references public.document_jobs(id) on delete cascade,
  part_id uuid references public.parts(id) on delete set null,
  part_number text,
  name text not null,
  quantity numeric(12,2) not null default 1 check (quantity > 0),
  unit_cost numeric(12,2) not null default 0 check (unit_cost >= 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  vat_rate numeric(5,2) not null default 13.50 check (vat_rate >= 0),
  fitted boolean not null default false,
  position integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  payment_number bigint generated by default as identity,
  invoice_id uuid not null references public.documents(id) on delete restrict,
  amount numeric(12,2) not null check (amount > 0),
  method text not null check (method in ('cash','card','bank_transfer','cheque')),
  paid_at timestamptz not null default now(),
  reference text,
  notes text,
  recorded_by uuid references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (organization_id, payment_number)
);

create table if not exists public.technician_time_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  technician_id uuid not null references public.profiles(id) on delete restrict,
  document_job_id uuid references public.document_jobs(id) on delete set null,
  event_type text not null check (event_type in ('clock_on','clock_off','lunch_start','lunch_end','manager_stop')),
  reason text,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_id uuid references public.profiles(id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists customers_organization_idx on public.customers(organization_id);
create index if not exists vehicles_customer_idx on public.vehicles(customer_id);
create index if not exists parts_search_idx on public.parts(organization_id, part_number, name);
create index if not exists documents_customer_idx on public.documents(customer_id, document_type, created_at desc);
create index if not exists documents_vehicle_idx on public.documents(vehicle_id, created_at desc);
create index if not exists document_jobs_document_idx on public.document_jobs(document_id, position);
create index if not exists payments_invoice_idx on public.payments(invoice_id, paid_at desc);
create index if not exists time_events_technician_idx on public.technician_time_events(technician_id, occurred_at desc);
create index if not exists audit_log_organization_idx on public.audit_log(organization_id, created_at desc);

alter table public.organizations enable row level security;
alter table public.profiles enable row level security;
alter table public.organization_members enable row level security;
alter table public.customers enable row level security;
alter table public.customer_contacts enable row level security;
alter table public.vehicles enable row level security;
alter table public.suppliers enable row level security;
alter table public.parts enable row level security;
alter table public.documents enable row level security;
alter table public.document_jobs enable row level security;
alter table public.document_parts enable row level security;
alter table public.payments enable row level security;
alter table public.technician_time_events enable row level security;
alter table public.audit_log enable row level security;

create policy "profiles_read_self_or_colleagues" on public.profiles for select to authenticated
using (id = auth.uid() or exists (
  select 1 from public.organization_members mine
  join public.organization_members theirs on theirs.organization_id = mine.organization_id
  where mine.user_id = auth.uid() and mine.active and theirs.user_id = profiles.id and theirs.active
));
create policy "profiles_update_self" on public.profiles for update to authenticated
using (id = auth.uid()) with check (id = auth.uid());

create policy "organizations_read_member" on public.organizations for select to authenticated
using (id in (select public.current_organization_ids()));
create policy "organizations_update_owner" on public.organizations for update to authenticated
using (public.has_organization_role(id, array['owner']))
with check (public.has_organization_role(id, array['owner']));

create policy "members_read_same_organization" on public.organization_members for select to authenticated
using (organization_id in (select public.current_organization_ids()));
create policy "members_manage_owner" on public.organization_members for all to authenticated
using (public.has_organization_role(organization_id, array['owner']))
with check (public.has_organization_role(organization_id, array['owner']));

create policy "customers_member_access" on public.customers for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "contacts_member_access" on public.customer_contacts for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "vehicles_member_access" on public.vehicles for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "suppliers_member_access" on public.suppliers for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "parts_member_access" on public.parts for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "documents_member_access" on public.documents for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "document_jobs_member_access" on public.document_jobs for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "document_parts_member_access" on public.document_parts for all to authenticated
using (organization_id in (select public.current_organization_ids()))
with check (organization_id in (select public.current_organization_ids()));
create policy "payments_read_member" on public.payments for select to authenticated
using (organization_id in (select public.current_organization_ids()));
create policy "payments_write_authorized" on public.payments for insert to authenticated
with check (public.has_organization_role(organization_id, array['owner','manager','front_of_house']));
create policy "time_events_read_member" on public.technician_time_events for select to authenticated
using (organization_id in (select public.current_organization_ids()));
create policy "time_events_insert_self_or_manager" on public.technician_time_events for insert to authenticated
with check (
  organization_id in (select public.current_organization_ids())
  and (technician_id = auth.uid() or public.has_organization_role(organization_id, array['owner','manager']))
);
create policy "audit_read_management" on public.audit_log for select to authenticated
using (public.has_organization_role(organization_id, array['owner','manager']));
create policy "audit_insert_member" on public.audit_log for insert to authenticated
with check (organization_id in (select public.current_organization_ids()) and actor_id = auth.uid());

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.customers, public.customer_contacts, public.vehicles,
  public.suppliers, public.parts, public.documents, public.document_jobs, public.document_parts to authenticated;
grant select, insert on public.payments, public.technician_time_events, public.audit_log to authenticated;
grant select on public.organizations, public.profiles, public.organization_members to authenticated;
grant update on public.organizations, public.profiles to authenticated;
grant insert, update, delete on public.organization_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
